ZF-55
folio-org/Net-Z3950-FOLIO pull request #22
Opened 2021-11-18 00:32 UTC by wafschneider

If restrictToItem is set, do not return a MARC holdings field for holdings records with no items.

2021-11-18 17:13 UTC, MikeTaylor requested changes
Apart from fixing the space/tab issue, the only other thing we need here is a `Changes.md` entry.

2021-11-18 17:13 UTC, MikeTaylor commented on lib/Net/Z3950/FOLIO/MARCHoldings.pm
>  	my $itemObjects = $holdingsMap->{circulations};
After a looong process of replicating this (on a box where I had not previously built this software, and in an adventure that involved creating https://github.com/MikeTaylor/yaz-config-polyfill ), I am finally able to verify that this not only looks right, it works right. Thank you for putting this together.

2021-11-18 20:57 UTC, wafschneider commented on lib/Net/Z3950/FOLIO/MARCHoldings.pm
>  	my $itemObjects = $holdingsMap->{circulations};
I've pushed an updated file with the indentation corrected, and added an `.editorconfig` file to at least document the convention. That is kind of a weird one, sorry I was unaware (`M-x indent-region` with the indent set to 4 and style set to space was the culprit for my initial commit). Thanks for reviewing, let me know if I got it right.

2021-11-18 21:00 UTC, MikeTaylor commented on lib/Net/Z3950/FOLIO/MARCHoldings.pm
>  	my $itemObjects = $holdingsMap->{circulations};
I don't blame you at all, I admit it is an objectively bad convention.

2021-11-18 21:20 UTC, MikeTaylor approved these changes
Looking good! Thank you for handling this.

2021-11-19 00:15 UTC, merged

2021-11-20 04:16 UTC, dcrossleyau commented
(The PR comments above lost their order flow, so continuing here.)

@MikeTaylor: Regarding Markdown line-breaks:

Oh, yeah i had not considered PDF.

Did some investigation today and found that another way to cause a hard line-break in documents generated from Markdown is to terminate the line with a backslash `\` e.g.\
rather than using the html `<br />` element.

See [example](https://github.com/folio-org/folio-org.github.io/commit/48295900c3adb42efca7cce368e2e62c2620ef04) in Markdown, and presented via the https://dev.folio.org/reference/api/#versioned-api-docs

My 'pandoc' is a bit old to attempt a proof demonstration, but i did find some useful resources. (I know that not all Markdown parsers support these methods.)

* https://stackoverflow.com/a/28283340 ("Pandoc Markdown enables the 'escaped_line_breaks' extension by default")
* https://github.github.com/gfm/#hard-line-break
* https://spec.commonmark.org/0.30/#hard-line-breaks

2021-11-22 11:04 UTC, MikeTaylor commented
Thanks for finding this -- it was new to me! It certainly works in PanDoc (with both HTML and PDF outputs) and in whatever random show-Markdown-as-HTML extension I have enabled in Chrome. If we are able to determine experimentally that it also works in GitHub's display of Markdown (which in practice is probably by far the most important use-case) we can make this our standard practice.

2021-11-23 01:23 UTC, dcrossleyau commented
Yes it does work with GitHub Flavored Markdown. See the spec links in my comment.

I did make two demos  to verify display via GitHub::
* My PR comment above has one for the line-break preceding "rather than using".
* [The source](https://github.com/folio-org/folio-org.github.io/blob/48295900c3adb42efca7cce368e2e62c2620ef04/reference/api/index.md#versioned-api-docs) of my "versioned-api-docs" demo.

2021-11-23 01:29 UTC, MikeTaylor commented
Excellent! Then that is what I will use going forward (assuming I remember). I think it's a terrible, terrible convention for a line-break; but still much less terrible than two trailing spaces!

2021-11-24 07:35 UTC, dcrossleyau commented
I followed through to add FAQ: https://dev.folio.org/faqs/how-to-use-editorconfig/

2021-11-24 10:55 UTC, MikeTaylor commented
Nice, thank you!